apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: f9q8kolfs-go 
  janus-idp.io/tekton: f9q8kolfs-go
  backstage.io/kubernetes-id: f9q8kolfs-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: f9q8kolfs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml