apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f9q8kolfs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f9q8kolfs-go 
  name: f9q8kolfs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f9q8kolfs-go 
